### ISSUE TITLE
Could not find "enzymes_s.pkl"

### ISSUE THREAD

**Issue by yzh119** [VoVAllen/diffpool#1]
BTW, please use the relative path instead of the absolute path, thx!

**Comment by yzh119** [comment]
well, it seems you should rename `enzymes.pkl` to `enzymes_s.pkl` also.

**Comment by VoVAllen** [comment]
我再检查一下，我有两个版本的dataset，有一个是从graph-pooling那个弄过来的，好像能train到60+
